ALTER TABLE order_items ADD COLUMN IF NOT EXISTS price_try NUMERIC;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS price_syp INTEGER;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS price_usd DOUBLE PRECISION;
